title: ANAM Craft Support
description: Your support portal for all things ANAM!
theme: just-the-docs

url: https://support.anamcraft.com

favicon_ico: /favicon.png

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
